import assert from "node:assert/strict";
const saved = new Map();
globalThis.localStorage = { getItem: (key) => saved.get(key) || null, setItem: (key, value) => saved.set(key, value) };
globalThis.window = new EventTarget();
const currency = await import("../js/currency.js");
let changes = 0;
window.addEventListener("currencychange", () => changes++);
assert.equal(currency.setCurrency("EUR"), true);
assert.equal(currency.currentCurrency(), "EUR");
assert.equal(currency.convertPrice(100), 93);
assert.equal(currency.setCurrency("INVALID"), false);
assert.equal(currency.currentCurrency(), "EUR");
assert.equal(changes, 1);
assert.equal(saved.get("mutuma.preferredCurrency"), "EUR");
const reloaded = await import("../js/currency.js?reload-test");
assert.equal(reloaded.currentCurrency(), "EUR");
globalThis.localStorage = { getItem() { throw new Error("Unavailable"); }, setItem() { throw new Error("Unavailable"); } };
assert.equal(currency.setCurrency("USD"), true);
assert.equal(currency.convertPrice(100), 100);
const { storeSettings } = await import("../js/site-settings.js");
assert.equal(storeSettings.fallbackOffer.discount_percent, 20);
console.log("Currency selection, persistence, invalid codes, private storage and 20% sale defaults passed.");
