import assert from "node:assert/strict";
process.env.SUPABASE_URL = "https://test.supabase.co";
process.env.SUPABASE_SECRET_KEY = "test";
process.env.SUPABASE_PUBLISHABLE_KEY = "test";
process.env.RESEND_API_KEY = "test";
process.env.RESEND_FROM_EMAIL = "orders@example.com";
process.env.SUPPORT_EMAIL = "support@example.com";
process.env.PUBLIC_SITE_URL = "https://example.com";
process.env.MAILERLITE_API_KEY = "test";
process.env.MAILERLITE_GROUP_ID = "123";
const { sendEmail } = await import("../netlify/functions/email-service.js");
const { syncNewsletter } = await import("../netlify/functions/newsletter-sync.js");
const { notifyOrder } = await import("../netlify/functions/order-email.js");
const { handler: contact } = await import("../netlify/functions/contact-message.js");
const { handler: retry } = await import("../netlify/functions/admin-retry-email.js");
const { handler: subscribe } = await import("../netlify/functions/subscribe-email.js");
const originalFetch = globalThis.fetch;
let calls = [];
let failure = false;
let order = { email: "buyer@example.com", payment_status: "paid", order_number: "ABC" };
const response = (data, status = 200) => new Response(JSON.stringify(data), { status });
globalThis.fetch = async (url, options = {}) => {
    const body = options.body ? JSON.parse(options.body) : null;
    calls.push({ url, options, body });
    if (url.includes("/auth/v1/user")) return response({}, 401);
    if (url.includes("api.resend.com")) return response(failure ? {} : { id: "email-id" }, failure ? 429 : 200);
    if (url.includes("connect.mailerlite.com")) return response({}, failure ? 503 : 200);
    if (url.includes("subscribers")) return response([{ email: "buyer@example.com" }]);
    if (options.method === "PATCH") { order = { ...order, ...body }; return response([order]); }
    return response([order]);
};
try {
    await syncNewsletter("buyer@example.com");
    assert.deepEqual(calls.at(-1).body, { email: "buyer@example.com", groups: ["123"] });
    const message = { to: "buyer@example.com", subject: "Order", text: "Thank you" };
    await sendEmail(message);
    const key = calls.at(-1).options.headers["Idempotency-Key"];
    await sendEmail(message);
    assert.equal(calls.at(-1).options.headers["Idempotency-Key"], key);
    assert.equal((await notifyOrder("ABC")).status, "accepted");
    const count = calls.filter(call => call.url.includes("api.resend.com")).length;
    await notifyOrder("ABC");
    assert.equal(calls.filter(call => call.url.includes("api.resend.com")).length, count);
    failure = true;
    assert.equal((await notifyOrder("ABC", "shipped")).status, "failed");
    assert.equal(order.email_notification.status, "failed");
    assert.equal(order.payment_status, "paid");
    failure = false;
    assert.equal((await notifyOrder("ABC", "shipped")).status, "accepted");
    order.payment_status = "refunded";
    await assert.rejects(notifyOrder("ABC"), /paid order/);
    assert.equal((await retry({ httpMethod: "POST", headers: {}, body: '{"orderNumber":"ABC"}' })).statusCode, 403);
    assert.equal((await contact({ httpMethod: "POST", body: "{" })).statusCode, 400);
    assert.equal((await contact({ httpMethod: "GET" })).statusCode, 405);
    const enquiry = { name: "Customer", email: "buyer@example.com", message: "Where is my order?" };
    assert.equal((await contact({ httpMethod: "POST", body: JSON.stringify(enquiry) })).statusCode, 200);
    assert.deepEqual(calls.at(-1).body.to, ["support@example.com"]);
    assert.equal(calls.at(-1).body.reply_to, enquiry.email);
    failure = true;
    assert.equal((await contact({ httpMethod: "POST", body: JSON.stringify(enquiry) })).statusCode, 503);
    const signup = await subscribe({ httpMethod: "POST", body: JSON.stringify({ email: enquiry.email }) });
    assert.equal(signup.statusCode, 503);
    assert.ok(calls.some(call => call.url.includes("supabase.co/rest/v1/subscribers") && call.options.method === "POST"));
    console.log("Email workflows: subscription, failure preservation, retry, duplicate protection, refund guard, contact delivery and admin authorisation passed.");
} finally { globalThis.fetch = originalFetch; }
