import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";
import { escapeHtml, safeImageUrl } from "../js/html.js";
import { productSeo } from "../js/seo.js";
assert.equal(escapeHtml('<img src=x onerror="bad">'), "&lt;img src=x onerror=&quot;bad&quot;&gt;");
assert.equal(safeImageUrl("javascript:alert(1)"), "/images/products/product-placeholder.svg");
assert.equal(safeImageUrl('data:text/html,evil'), "/images/products/product-placeholder.svg");
assert.equal(safeImageUrl('images/products/rug.jpg'), 'images/products/rug.jpg');
assert.equal(productSeo(null), null);
const seo = productSeo({ id: "a&b", name: "A rug", images: [] });
assert.equal(seo.url, "https://mutumas.com/product?id=a%26b");
assert.equal(seo.title, "A rug | MUTUMA");
assert.ok(seo.image.endsWith("product-placeholder.svg"));
const source = await readFile(new URL("../js/ui.js", import.meta.url), "utf8");
const imageFunction = source.slice(source.indexOf("export function productImage("), source.indexOf("function optionDots("));
const context = vm.createContext({ escapeHtml, safeImageUrl, location: { hostname: "mutumas.com" } });
vm.runInContext(imageFunction.replace("export ", ""), context);
const markup = context.productImage("images/products/rug.jpg", '<rug "name">');
assert.match(markup, /srcset=/);
assert.match(markup, /loading="lazy"/);
assert.match(markup, /alt="&lt;rug &quot;name&quot;&gt;"/);
const missing = context.productImage(null, "Missing image");
assert.match(missing, /src="\/images\/products\/product-placeholder.svg"/);
const onerror = markup.match(/onerror="([^"]+)"/)[1];
const failedImage = { srcset: "responsive", src: "original", removeAttribute() { this.srcset = ""; } };
vm.runInNewContext(`(function(){${onerror}}).call(image)`, { image: failedImage });
assert.equal(failedImage.src, "original");
vm.runInNewContext(`(function(){${onerror}}).call(image)`, { image: failedImage });
assert.equal(failedImage.src, "/images/products/product-placeholder.svg");
assert.equal(failedImage.onerror, null);
console.log("HTML escaping, safe images and product metadata tests passed.");
